// src/main.tsx
// ============================================================================
// 🎯 main.tsx — Entry point with PWA service worker registration
// ============================================================================
// Fixes P2 #19. Registers the SW (auto-generated by vite-plugin-pwa) and
// shows a non-blocking toast when an update is available.
// ============================================================================

import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { registerSW } from 'virtual:pwa-register';

import App from './App';
import { AuthProvider } from './contexts/AuthContext';
import { NotificationProvider } from './contexts/NotificationContext';
import { TutorialProvider } from './contexts/TutorialContext';
import './index.css';

// ============================================================================
// PWA service worker
// ============================================================================
const updateSW = registerSW({
  onNeedRefresh() {
    // Show a non-blocking toast (handled inside the app via custom event)
    window.dispatchEvent(
      new CustomEvent('pwa:update-available', {
        detail: {
          accept: () => updateSW(true),
        },
      })
    );
  },
  onOfflineReady() {
    console.info('[PWA] Application prête à fonctionner hors ligne.');
  },
  onRegistered(r) {
    // Re-check for updates every hour while the app is open
    if (r) {
      setInterval(() => r.update(), 60 * 60 * 1000);
    }
  },
  onRegisterError(error) {
    console.error('[PWA] SW registration error:', error);
  },
});

// ============================================================================
// Mount
// ============================================================================
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <AuthProvider>
        <NotificationProvider>
          <TutorialProvider>
            <App />
          </TutorialProvider>
        </NotificationProvider>
      </AuthProvider>
    </BrowserRouter>
  </React.StrictMode>
);
